theme: jekyll-theme-minimal
title: Resume for Skyla Dudek
description: Please view my resume to learn about me.
description: You can view my README file to learn how to host your own resume on Github pages!
author: Skyla Dudek
published: true
date: 2019-10-31
